### ISSUE TITLE
Interesting!

### ISSUE THREAD

**Issue by paaljoachim** [AnitaYCheng/ParallaxFeaturedImage#1]
Hey

Your snippet looks really interesting. (I tried it out and am thinking of using this for one of my web pages.)

Do you have any real world cases you can demo to add to your readme?

**Comment by AnitaYCheng** [comment]
Yes! It's functioning on http://www.flyingeyes.biz. I have a more robust explanation about how to implement it on my blog here: http://anitacheng.com/parallax-scrolling-featured-image-in-wordpress-genesis

I will add them to the readme ASAP. Thanks for pointing it out - I actually didn't expect people to find it here, haha.

**Comment by paaljoachim** [comment]
Great!
